export const metadata = {
  name: 'Electrochemical Measurement',
  description: 'Various electrochemical measurement techniques including OCV, CP, CVA, PEIS, and LSV',
  category: 'measurement',
  version: '1.0.0',
  author: 'SDL1 Team',
  tags: ['electrochemistry', 'measurement', 'potentiostat', 'impedance', 'voltammetry'],
  capabilities: [
    'Open Circuit Voltage (OCV) measurement',
    'Chronopotentiometry (CP) with voltage limits',
    'Potentiostatic Electrochemical Impedance Spectroscopy (PEIS)',
    'Cyclic Voltammetry (CVA) - in development',
    'Linear Sweep Voltammetry (LSV) - in development',
    'Automated data recording',
  ],
  limitations: [
    'Single measurement type per execution',
    'CVA and LSV parameters not yet implemented',
    'No real-time data visualization',
    'Fixed sampling rates',
  ],
  primitiveOperations: [
    'connect_electrodes',
    'initialize_potentiostat',
    'measure_ocv',
    'apply_current',
    'apply_voltage',
    'measure_impedance',
    'record_data',
    'disconnect_electrodes',
    'wait',
  ],
  requiredResources: [
    'Potentiostat/Galvanostat',
    'Connected electrodes (RE, CE, WE)',
    'Electrochemical cell',
    'Data acquisition system',
  ],
};