apiVersion: v1
kind: Secret
metadata:
  name: workflow-secrets
  namespace: workflow-management
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql://workflow_user:REPLACE_WITH_SECURE_PASSWORD@postgres-service:5432/workflow_management"
  POSTGRES_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"
  
  # Application secrets
  SECRET_KEY: "REPLACE_WITH_SECURE_SECRET_KEY"
  
  # Redis URL
  REDIS_URL: "redis://redis-service:6379"
  
  # AWS credentials (if using S3)
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET_KEY"
  S3_BUCKET: "workflow-files-production"
  S3_REGION: "us-east-1"
  
  # Monitoring
  SENTRY_DSN: "https://your-production-sentry-dsn@sentry.io/project-id"
  
---
# TLS Secret for HTTPS (replace with your certificates)
apiVersion: v1
kind: Secret
metadata:
  name: workflow-tls
  namespace: workflow-management
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace these with your actual certificate data
  tls.crt: LS0tLS1CRUdJTi0tLS0t...
  tls.key: LS0tLS1CRUdJTi0tLS0t...