export const metadata = {
  name: 'Wash/Cleaning',
  description: 'Electrode and reactor cleaning operations for electrochemical experiments',
  category: 'cleaning',
  version: '1.0.0',
  author: 'SDL1 Team',
  tags: ['cleaning', 'wash', 'maintenance', 'ultrasonic', 'electrochemistry'],
  capabilities: [
    'Automated cleaning tool handling',
    'Dual pump cleaning solution dispensing',
    'Ultrasonic cleaning activation',
    'Multiple cleaning cycles',
    'Waste aspiration',
    'Configurable insertion depth',
  ],
  limitations: [
    'Single well cleaning per execution',
    'Fixed cleaning tool positions',
    'No temperature control',
    'No cleaning solution mixing',
  ],
  primitiveOperations: [
    'pick_cleaning_tool',
    'move_to_well',
    'insert_tool',
    'dispense_cleaning_solution',
    'activate_ultrasonic',
    'aspirate_waste',
    'retract_tool',
    'return_tool',
    'wait',
  ],
  requiredResources: [
    'Cleaning tool gripper',
    'Cleaning tool',
    'Pump 1 with cleaning solution',
    'Pump 2 with cleaning solution',
    'Ultrasonic transducer',
    'Waste aspiration system',
  ],
};