name: Deploy Canvas Frontend

on:
  push:
    branches: [main]  # 每次 push 到 main 分支就触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-deployment  # 对应 GitHub 环境变量设置（可选）

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: src
      run: npm install

    - name: Build frontend
      working-directory: src
      run: npm run build

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync src/dist s3://$S3_BUCKET_NAME --delete

    - name: Invalidate CloudFront cache
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
